# Generated by Django 4.1 on 2022-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_alter_advertisment_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
