# Generated by Django 4.1 on 2022-09-02 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0003_alter_advertisment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
