# Generated by Django 4.1 on 2022-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0004_alter_advertisment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default='default.png', upload_to='advertisment_photos'),
        ),
    ]
