# Generated by Django 4.1 on 2022-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0006_advertisment_category_alter_advertisment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
