# Generated by Django 4.1 on 2022-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0007_alter_advertisment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='advertisment_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
