# Generated by Django 4.1 on 2022-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0009_testadvertisment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testadvertisment',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
