# Generated by Django 4.1 on 2022-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0010_alter_testadvertisment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testadvertisment',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
