# Generated by Django 4.1 on 2022-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0012_alter_advertisment_advertisment_url_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testadvertisment',
            table='test_advertisment_2',
        ),
    ]
