# Generated by Django 4.1 on 2022-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0013_alter_testadvertisment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAdvertisment',
        ),
    ]
