# Generated by Django 4.1 on 2022-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0015_testadvertisment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='advertisment_photos'),
        ),
        migrations.AlterField(
            model_name='testadvertisment2',
            name='advertisment_url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testadvertisment2',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='advertisment_photos'),
        ),
        migrations.AlterField(
            model_name='testadvertisment2',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
