# Generated by Django 4.1 on 2022-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0016_alter_advertisment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=1000, null=True, upload_to='advertisment_photos'),
        ),
        migrations.AlterField(
            model_name='testadvertisment2',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=1000, null=True, upload_to='advertisment_photos'),
        ),
    ]
