# Generated by Django 4.1 on 2022-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0017_alter_advertisment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='scraped_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='testadvertisment2',
            name='scraped_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
