# Generated by Django 4.1 on 2022-09-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0019_category_scrapedadvertisment2_uploadedadvertisment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedAdvertisment2',
            new_name='ScrapedAdvertisment',
        ),
    ]
