# Generated by Django 4.1 on 2022-09-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0023_alter_uploadedadvertisment_advertisment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='advertisment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_advertisment', to='cars_api.advertisment'),
        ),
    ]
