# Generated by Django 4.1 on 2022-09-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0026_alter_scrapedadvertisment_advertisment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedadvertisment',
            name='advertisment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_advertisment', to='cars_api.advertisment'),
        ),
    ]
