# Generated by Django 4.1 on 2022-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0027_alter_scrapedadvertisment_advertisment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedadvertisment',
            old_name='uploaded_by',
            new_name='uploaded_by_user',
        ),
    ]
