# Generated by Django 4.1 on 2022-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0029_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='slug',
            field=models.SlugField(default='default', max_length=250),
        ),
    ]
