# Generated by Django 4.1 on 2022-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0031_alter_advertisment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='slug',
            field=models.SlugField(default='', max_length=1000),
        ),
    ]
