# Generated by Django 4.1 on 2022-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0033_alter_advertisment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedadvertisment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='uploadedadvertisment',
            name='price',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
