# Generated by Django 4.1 on 2022-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0034_remove_scrapedadvertisment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedadvertisment',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
