# Generated by Django 4.1 on 2022-09-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_api', '0039_alter_advertisment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapedadvertisment',
            name='advertisment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraped_advertisment', to='cars_api.advertisment'),
        ),
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='advertisment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_advertisment', to='cars_api.advertisment'),
        ),
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=1000, null=True, upload_to='advertisment_photos'),
        ),
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='uploaded_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_advertisments', to=settings.AUTH_USER_MODEL),
        ),
    ]
