# Generated by Django 4.1 on 2022-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0040_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='image',
            field=models.ImageField(default='default.png', max_length=1000, upload_to='advertisment_photos'),
        ),
    ]
