# Generated by Django 4.1 on 2022-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0041_alter_uploadedadvertisment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedadvertisment',
            name='image',
            field=models.ImageField(blank=True, default='default.png', max_length=1000, null=True, upload_to='advertisment_photos'),
        ),
    ]
