from django.urls import path

from .views import (
    BlacklistTokenView, AdvertismentSearch,
    CategoryList,
    UserDetail, UserCreateView,
    UserUpdateView, UserGoogleLogin,
    AdvertismentList, AdvertismentDetial,
    AdvertismentCreate, AdvertismentUpdate,
    AdvertismentDelete
)

urlpatterns = [
    path('logout/',
         BlacklistTokenView.as_view(),
         name='logout'),
    path('search/',
         AdvertismentSearch.as_view(),
         name='advertisment-search'),
    path('categories/',
         CategoryList.as_view(),
         name='category-list'),
    path('users/<int:pk>/',
         UserDetail.as_view(),
         name='user-detail'),
    path('user/register/',
         UserCreateView.as_view(),
         name='register'),
    path('users/update/<int:pk>/',
         UserUpdateView.as_view(),
         name='user-update'),
    path('users/google-login/',
         UserGoogleLogin.as_view(),
         name='user-google-login'),
    path('advertisments/',
         AdvertismentList.as_view(),
         name='advertisment-list'),
    path('advertisments/<int:pk>/',
         AdvertismentDetial.as_view(),
         name='advertisment-detail'),
    path('advertisments/create/',
         AdvertismentCreate.as_view(),
         name='advertisment-create'),
    path('advertisments/update/<int:pk>/',
         AdvertismentUpdate.as_view(),
         name='advertisment-update'),
    path('advertisments/delete/<int:pk>/',
         AdvertismentDelete.as_view(),
         name='advertisment-delete'),
]
